### ISSUE TITLE
Give GitHub Actions access to some of our GitLab repos

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#11]
- [ ] Give GitHub Actions access to our `wordpress-{themes,plugins}` repos
- [ ] Revert this: https://github.com/dxw/wordpress-template/commit/8e8584c192fd944dc6c649a648ba300d30692dfc

**Comment by snim2** [comment]
@RobjS I don't think we don't run `whippet deps install` in the CI pipeline, but I think this can probably be closed?

**Comment by RobjS** [comment]
Yes, we have an action that validates the Whippet files now (which was the intention behind this).
