### ISSUE TITLE
Repos created with this template should be able to update themselves

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#3]
There should be a script in `bin/` or `script/` that updates the files to the latest version found in this template.

**Comment by RobjS** [comment]
@mallorydxw Do you have an example scenario in mind? The main one I can think of is if we want to update the docker-compose setup (e.g. like the time we had to replace mysql with mariadb).

If the files are expected to be automatically updated, I feel like they should probably live in `vendor/` as a composer package as far as possible, as it'd be reasonable to expect that anything outside of there is manually editable and those edits won't be over-written by an auto-update.

**Comment by mallorydxw** [comment]
I think #4 seems like the most sensible way to make this happen. So I'll close this.
