### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#32]
They're currently showing our old logo:

https://github.com/dxw/wordpress-template/tree/4a427936d348eb1897189abde3120f79cb44dd87/wp-content/themes/theme/assets/img

Since most sites we make won't be our own sites, we shouldn't use our actual logo.

I won't link it here, but in our Brand Toolkit, it says one of our shapes is a circle. We can just make the new favicons circles in one of our brand colours. This will fit with the brand without being our actual logo.

**Comment by snim2** [comment]
This was resolved in 10fd4e31c6724c28d6d18bcf8b29403c1894bd1e
