### ISSUE TITLE
Tighten up our .gitignore files & rules

### ISSUE THREAD

**Issue by RobjS** [dxw/wordpress-template#53]
We should modify our `.gitignore` file to bring it more line with the modified rails template equivalent: https://github.com/dxw/rails-template/pull/198

This will: 
* Make it easier to read & manage
* Help us to avoid committing files we don't want committed

We currently have 2 `.gitignore`s in use, one at the top level and one in `wp-content/themes/theme`. 

(Note: there's actually a third empty `.gitignore` in `wp-content/plugins`, but we should just remove that).

My initial thought was to consolidate the two active `.gitignore`s into a single top-level `.gitignore`, for clarity.

However, Whippet's `generate theme` command produces a copy of the `wp-content/theme` directory from this repo. That generated theme could then potentially be used as a standalone repo, or be used within an existing project based on this template. In the former case, it would be useful to have a `.gitignore` file included as part of the generated theme, so removing it altogether would be potentially counter-productive. In the latter case, we don't want the extra `.gitignore`.

Options that immediately spring to mind:

1. Continue following the model we have now. Use the top-level `.gitignore` to manage global rules for e.g. potentially risky file types, and use the theme-level `.gitignore` for managing rules at a theme level.
1. Consolidate to a single top-level `.gitignore`, and accept that if we use `whippet generate theme` to create a theme that's going to be in a standalone repo, we have to manually create a suitable `.gitignore` file for that repo
1. Consolidate to single top-level `.gitignore`, and add an option to `whippet generate theme` to tell it if you want a `.gitignore` included (e.g. `whippet generate theme --withgitignore`), in which case it'll take a copy of the top-level `.gitignore` from this repo and add it to the theme it generates.

**Comment by RobjS** [comment]
Tagging in @erbridge and @dxw-serena for opinions on this.

**Comment by erbridge** [comment]
I'd be inclined to go with option 3, but reverse the default behaviour (have it opt out instead of opt in). Basically, whatever means you get a good `.gitignore` by default without having to think about it. If it's something you have to opt into, sometimes you're going to forget.

**Comment by RobjS** [comment]
Resolved by #56
